### ISSUE TITLE
Please set read-rights for produced datacube.nt

### ISSUE THREAD

**Issue by k00ni** [AKSW/transform-bvl-csv-to-datacube#7]
In my current setup i got `datacube.nt` with the following file permissions:

`-rw------- 1 root  root     48971 Dez 12 15:37 datacube.nt`

Please change process, that i can at least read the file.

**Comment by GeorgesAlkhouri** [comment]
This issue is docker related. The default docker user is the **root user**, so every file created by the docker container will be created from a root user and hence you'll need root status to do something with them.

Even if you **create a not root user** for the container the files may be have the wrong permissions on your host system because the **created user has a user id which does not match** with that one on your host system. 

Also, even if the user id match with your host system it will vary from every other host system which will use this docker image.

**Comment by k00ni** [comment]
Ok, there are problems with the user ID. But i still not understand, why giving the file **read rights** is so difficult? I already have containers which produce readable files.
